[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
sha256 = "1.5.0"
primitive-types = "0.13.1"
rustc-hex = "2.1.0"
uint = "0.10.0"
k256 = "0.13.4"
rand = "0.8.5"   # ✅ Use rand 0.8 (compatible with k256)
